config/routes.rb
Rails.application.routes.draw do
  
  resources :topics do
    resources :posts, except: [:index]
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
    
  end
  
  resources :users, only: [:new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :topic
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    default_scope { order('rank DESC') }
    
    scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
    
    validates :title, length: { minimum: 5 }, presence: true
    validates :body, length: { minimum: 20 }, presence: true
    validates :topic, presence: true
    validates :user, presence: true
    
    def up_votes
        votes.where(value: 1).count
    end
    
    def down_votes
        votes.where(value: -1).count
    end
    
    def points
        votes.sum(:value)
    end
    
    def update_rank
        age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
        new_rank = points + age_in_days
        update_attribute(:rank, new_rank)
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :require_sign_in, except: :show
  before_action :moderator_user, only: [:edit, :update]
  before_action :authorize_user, only: :destroy
  
  
  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end
  
  def create
    
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    @post.user = current_user
    
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)

    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end
  
  def destroy
    
    @post = Post.find(params[:id])
    
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
    
    def authorize_user
      post = Post.find(params[:id])
      unless current_user == post.user || current_user.admin?
        flash[:alert] = "You must be an admin to do that."
        redirect_to [post.topic, post]
      end
    end
    
    def moderator_user
      post = Post.find(params[:id])
      unless current_user == post.user || !current_user.member?
        flash[:alert] = "You must be an admin or moderator to do that."
        redirect_to [post.topic, post]
      end
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
    def user_is_authorized_for_post?(post)
        current_user && (current_user == post.user || current_user.admin?)
    end
    
    def user_is_authorized_edit_post?(post)
        current_user && (current_user == post.user || current_user.admin? || current_user.moderator?)
    end
    
end

app/views/posts/_form.html.erb
 <%= form_for [topic, post] do |f| %>
   
   <% if post.errors.any? %>
   
       <div class="alert alert-danger">
           <h4><%= pluralize(post.errors.count, "error") %>.</h4>
           <ul>
               <% post.errors.full_messages.each do |msg| %>
                   <li><%= msg %></li>
               <% end %>
           </ul>
       </div>
   <% end %>
   
   <%= form_group_tag(post.errors[:title]) do %>
     <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
   <% end %>
   <%= form_group_tag(post.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/posts/_post.html.erb
 <div class="media">
   <%= render partial: 'votes/voter', locals: { post: post } %>
   <div class="media-body">
     <h4 class="media-heading">
       <%= link_to post.title, topic_post_path(post.topic, post) %>
     </h4>
     <small>
       submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
       <%= post.comments.count %> Comments
     </small>
   </div>
 </div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
        <ul>
            <li>Make sure it rhymes.</li>
            <li>Don't use the letter "A".</li>
            <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>

    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
    </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
        <ul>
            <li>Make sure it rhymes.</li>
            <li>Don't use the letter "A".</li>
            <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>

    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
    </div>
</div>

app/views/posts/show.html.erb
<div>
    <%= render partial: 'votes/voter', locals: { post: @post } %>
    <h1>
        <%= @post.title %><br>
        <small>
            submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
        </small>
    </h1>
</div>

<div class="row">
    <div class="col-md-8">
        <p><%= @post.body %></p>
        <div>
            <h3>Comments</h3>
            <%= render @post.comments %>
        </div>
        <% if current_user %>
            <%= render 'comments/form', comment: Comment.new, post: @post %>
        <% end %>
    </div>
    <% if user_is_authorized_for_post?(@post) %>
        <div class="col-md-4">
            <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: "btn btn-success" %>
            <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure you want to delete this post?"} %>
        </div>
    <% end %>
    <div class="col-md-4">
        <h3>
            <%= pluralize(@post.points, 'point') %>
            <div>
                <small>
                    <%= pluralize(@post.up_votes, 'up vote') %>
                    <%= pluralize(@post.down_votes, 'down vote') %>
                </small>
            </div>
        </h3>
        <% if current_user %>
            <%= render partial: 'favorites/favorite', locals: { post: @post } %>
        <% end %>
    </div>
</div>