config/routes.rb
Rails.application.routes.draw do
  
  resources :topics do
    resources :posts, except: [:index]
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
    
  end
  
  resources :users, only: [:new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  
  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true
  
  after_create :send_favorite_emails
  
  private
  
  def send_favorite_emails
    post.favorites.each do |favorite|
      FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
    end
  end
  
  
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :topic
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    default_scope { order('rank DESC') }
    
    scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
    
    validates :title, length: { minimum: 5 }, presence: true
    validates :body, length: { minimum: 20 }, presence: true
    validates :topic, presence: true
    validates :user, presence: true
    
    def up_votes
        votes.where(value: 1).count
    end
    
    def down_votes
        votes.where(value: -1).count
    end
    
    def points
        votes.sum(:value)
    end
    
    def update_rank
        age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
        new_rank = points + age_in_days
        update_attribute(:rank, new_rank)
    end
    
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
    has_many :posts, dependent: :destroy
    
    validates :name, length: {minimum: 5 }, presence: true
    validates :description, length: { minimum: 15 }, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    before_save { self.email = email.downcase if email.present? }
    before_save { self.role ||= :member }
    
    validates :name, length: { minimum: 1, maximum: 100 }, presence: true
    validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
    validates :password, length: { minimum: 6 }, allow_blank: true
    
    validates :email,
                presence: true,
                uniqueness: { case_sensitive: false },
                length: { minimum: 3, maximum: 254 }
                
    has_secure_password
    
    enum role: [:member, :admin]
    
    def favorite_for(post)
        favorites.where(post_id: post.id).first
    end
    
    def avatar_url(size)
        gravatar_id = Digest::MD5::hexdigest(self.email).downcase
        "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    end
    
    def favorite_for(post)
        favorites.where(post_id: post.id).first
    end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post
  
  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true
  
  private
  
  def update_post
    post.update_rank
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def form_group_tag(errors, &block)
        css_class = 'form-group'
        css_class << ' has-error' if errors.any?
        
        content_tag :div, capture(&block), class: css_class
    end
    
    def avatar_url(user)
        gravatar_id = Digest::MD5::hexdigest(user.email).downcase
         "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
    def user_is_authorized_for_comment?(comment)
        current_user && (current_user == comment.user || current_user.admin?)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def user_is_authorized_for_post?(post)
        current_user && (current_user == post.user || current_user.admin?)
    end
    
    def user_is_authorized_edit_post?(post)
        current_user && (current_user == post.user || current_user.admin? || current_user.moderator?)
    end
    
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def create_session(user)
        session[:user_id] = user.id
    end
    
    def destroy_session(user)
        session[:user_id] = nil
    end
    
    def current_user
        User.find_by(id: session[:user_id])
    end
    
end

app/helpers/topics_helper.rb
module TopicsHelper
    
    def user_is_authorized_for_topics?
        current_user && current_user.admin?
    end
    
    def user_is_authorized_edit_topics?
        current_user && (current_user.admin? || current_user.moderator?)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
    def user_created_posts?(user)
        user.posts.any?
    end
    def user_created_comments?(user)
        user.comments.any?
    end
    def user_favorited_posts?(user)
        user.favorites.any?
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
      <li><%= link_to "About", about_path %></li>

      <div class="pull-right user-info">
      <% if current_user %>
        <%= image_tag current_user.avatar_url(48), class: "gravatar" %>
        <div class="pull-right">
          <%= link_to current_user.name, user_path(current_user) %> <br /> <%= link_to "Sign Out", session_path(current_user), method: :delete %>
        </div>
        <% else %>
          <%= link_to "Sign In", new_session_path %> or
          <%= link_to "Sign Up", new_user_path %>
        <% end %>
      </div>

    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>   
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>